### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tavery321** [rmccorm4/first-flask-app#1]
Please make it work

**Comment by rmccorm4** [comment]
Hi @tavery321,

Thanks for bringing up this issue! We are working as hard as we can to fix this issue as quickly as possible, please bear with us.

Thanks,
The team at first-flask-app

**Comment by tavery321** [comment]
Wow great customer service I'd like to fund this application

**Comment by tavery321** [comment]
Wow that looks really good
